# Generated by Django 2.1 on 2018-09-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('series_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('title', models.TextField(default='')),
                ('document', models.TextField(default='')),
                ('publication_at', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=128, null=True)),
                ('source_url', models.CharField(max_length=1024, null=True)),
                ('source_type', models.IntegerField(default=-1)),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField()),
                ('extra', models.TextField(null=True)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('series_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('object_type', models.IntegerField()),
                ('object_id', models.CharField(max_length=128)),
                ('content', models.TextField(default='')),
                ('article_url', models.CharField(max_length=1024, null=True)),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField()),
                ('extra', models.TextField(null=True)),
            ],
            options={
                'db_table': 'keyword',
            },
        ),
        migrations.CreateModel(
            name='PostBar',
            fields=[
                ('series_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('theme_id', models.CharField(max_length=128)),
                ('floor_id', models.CharField(max_length=128)),
                ('title', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('source_url', models.CharField(max_length=1024, null=True)),
                ('publication_at', models.IntegerField(null=True)),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField()),
                ('extra', models.TextField(null=True)),
            ],
            options={
                'db_table': 'post_bar',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('series_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('object_type', models.IntegerField()),
                ('object_id', models.CharField(max_length=128)),
                ('content', models.TextField(default='')),
                ('upvote_num', models.IntegerField(null=True)),
                ('publication_at', models.IntegerField(null=True)),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField()),
                ('extra', models.TextField(null=True)),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['object_type', 'object_id'], name='object_type_id_index'),
        ),
        migrations.AddIndex(
            model_name='postbar',
            index=models.Index(fields=['theme_id', 'floor_id'], name='theme_floor_index'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['object_type', 'object_id'], name='object_type_id_index'),
        ),
    ]
