# Generated by Django 2.1 on 2018-09-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0003_postbar_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='series_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postbar',
            name='floor_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='postbar',
            name='series_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postbar',
            name='theme_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='review',
            name='object_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='review',
            name='series_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
